
package ru.sample.qiwi.beelinesoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoringAndVerificationInterface", targetNamespace = "urn:gf-scoring-verification:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScoringAndVerificationInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.sample.qiwi.beelinesaop.Approval3RdPartyResponse
     * @throws SystemFault
     * @throws LogicFault
     * @throws ValidationFault
     */
    @WebMethod(operationName = "approval3rdParty")
    @WebResult(name = "approval3rdPartyResponse", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
    public Approval3RdPartyResponse approval3RdParty(
        @WebParam(name = "approval3rdPartyRequest", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
        Approval3RdPartyRequest parameters)
        throws LogicFault, SystemFault, ValidationFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.sample.qiwi.beelinesaop.GetScoringAndVerification3SdPartyResponse
     * @throws SystemFault
     * @throws LogicFault
     * @throws ValidationFault
     */
    @WebMethod(operationName = "getScoringAndVerification3sdParty")
    @WebResult(name = "getScoringAndVerification3sdPartyResponse", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
    public GetScoringAndVerification3SdPartyResponse getScoringAndVerification3SdParty(
        @WebParam(name = "getScoringAndVerification3sdPartyRequest", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
        GetScoringAndVerification3SdPartyRequest parameters)
        throws LogicFault, SystemFault, ValidationFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.sample.qiwi.beelinesaop.GetScoringSMSResponse
     * @throws LogicFault
     * @throws SystemFault
     * @throws ValidationFault
     */
    @WebMethod
    @WebResult(name = "getScoringSMSResponse", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
    public GetScoringSMSResponse getScoringSMS(
        @WebParam(name = "getScoringSMSRequest", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
        GetScoringSMSRequest parameters)
        throws LogicFault, SystemFault, ValidationFault
    ;

}
