
package ru.sample.qiwi.beelinesoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoringCallBackInterface", targetNamespace = "urn:gf-scoring-verification:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScoringCallBackInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.sample.qiwi.beelinesaop.GetScoringAndVerification3SdPartyCallBackResponse
     * @throws LogicFault
     * @throws SystemFault
     * @throws ValidationFault
     */
    @WebMethod(operationName = "getScoringAndVerification3sdPartyCallBack")
    @WebResult(name = "getScoringAndVerification3sdPartyCallBackResponse", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
    public GetScoringAndVerification3SdPartyCallBackResponse getScoringAndVerification3SdPartyCallBack(
        @WebParam(name = "getScoringAndVerification3sdPartyCallBackRequest", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
        GetScoringAndVerification3SdPartyCallBackRequest parameters)
        throws LogicFault, SystemFault, ValidationFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.sample.qiwi.beelinesaop.GetScoringSMSCallBackResponse
     * @throws SystemFault
     * @throws LogicFault
     * @throws ValidationFault
     */
    @WebMethod
    @WebResult(name = "getScoringSMSCallBackResponse", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
    public GetScoringSMSCallBackResponse getScoringSMSCallBack(
        @WebParam(name = "getScoringSMSCallBackRequest", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
        GetScoringSMSCallBackRequest parameters)
        throws LogicFault, SystemFault, ValidationFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.sample.qiwi.beelinesaop.GetScoringSMSCallBackResponse
     * @throws LogicFault
     * @throws SystemFault
     * @throws ValidationFault
     */
    @WebMethod
    @WebResult(name = "getScoringRequestOfSubscriberResponse", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
    public GetScoringSMSCallBackResponse getScoringRequestOfSubscriber(
        @WebParam(name = "getScoringRequestOfSubscriberRequest", targetNamespace = "urn:gf-scoring-verification:types", partName = "parameters")
        GetScoringSMSCallBackRequest parameters)
        throws LogicFault, SystemFault, ValidationFault
    ;

}
