
package ru.sample.qiwi.beelinesoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoringCallBackService", targetNamespace = "urn:gf-scoring-verification:wsdl", wsdlLocation = "file:/C:/Users/\u0414\u043c\u0438\u0442\u0440\u0438\u0439%20\u0410\u0441\u0442\u0430\u0445\u043e\u0432/AppData/Local/Temp/tempdir8076691759686742632.tmp/Scoring_1.wsdl")
public class ScoringCallBackService
    extends Service
{

    private final static URL SCORINGCALLBACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORINGCALLBACKSERVICE_EXCEPTION;
    private final static QName SCORINGCALLBACKSERVICE_QNAME = new QName("urn:gf-scoring-verification:wsdl", "ScoringCallBackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/\u0414\u043c\u0438\u0442\u0440\u0438\u0439%20\u0410\u0441\u0442\u0430\u0445\u043e\u0432/AppData/Local/Temp/tempdir8076691759686742632.tmp/Scoring_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORINGCALLBACKSERVICE_WSDL_LOCATION = url;
        SCORINGCALLBACKSERVICE_EXCEPTION = e;
    }

    public ScoringCallBackService() {
        super(__getWsdlLocation(), SCORINGCALLBACKSERVICE_QNAME);
    }

    public ScoringCallBackService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORINGCALLBACKSERVICE_QNAME, features);
    }

    public ScoringCallBackService(URL wsdlLocation) {
        super(wsdlLocation, SCORINGCALLBACKSERVICE_QNAME);
    }

    public ScoringCallBackService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORINGCALLBACKSERVICE_QNAME, features);
    }

    public ScoringCallBackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoringCallBackService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScoringCallBackInterface
     */
    @WebEndpoint(name = "ScoringCallBackPort")
    public ScoringCallBackInterface getScoringCallBackPort() {
        return super.getPort(new QName("urn:gf-scoring-verification:wsdl", "ScoringCallBackPort"), ScoringCallBackInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoringCallBackInterface
     */
    @WebEndpoint(name = "ScoringCallBackPort")
    public ScoringCallBackInterface getScoringCallBackPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:gf-scoring-verification:wsdl", "ScoringCallBackPort"), ScoringCallBackInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORINGCALLBACKSERVICE_EXCEPTION!= null) {
            throw SCORINGCALLBACKSERVICE_EXCEPTION;
        }
        return SCORINGCALLBACKSERVICE_WSDL_LOCATION;
    }

}
