
package ru.sample.qiwi.soap.ru.mbtc.afs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "match", targetNamespace = "http://mbtc.ru/afs/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Match {


    /**
     * 
     * @param afsRequest
     * @return
     *     returns ru.sample.qiwi.soap.ru.mbtc.afs.AfsResponseType
     */
    @WebMethod(action = "http://mbtc.ru/afs/match")
    @WebResult(name = "afsResponse", targetNamespace = "http://mbtc.ru/afs", partName = "afsResponse")
    public AfsResponseType match(
        @WebParam(name = "afsRequest", targetNamespace = "http://mbtc.ru/afs", partName = "afsRequest")
        AfsRequestType afsRequest);

}
