
package ru.sample.qiwi.soap.cre2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * ��������� ���-�������
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SingleFormatService", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SingleFormatService {


    /**
     * 
     * @param requestData
     * @return
     *     returns ru.sample.qiwi.ProcessRequestOut
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestWSI")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "report")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestWSIResponse")
    public ProcessRequestOut processRequestWSI(
            @WebParam(name = "ProcessRequestData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "requestData")
            ProcessRequestData requestData);

    /**
     * 
     * @param requestData
     * @return
     *     returns ru.sample.qiwi.ProcessRequestOut
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestWSI")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestWSIResponse")
    public ProcessRequestOut groupRequestWSI(
            @WebParam(name = "GroupRequestData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "requestData")
            GroupRequestData requestData);

    /**
     * 
     * @param requestData
     * @return
     *     returns ru.sample.qiwi.ProcessRequestOut
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateWSI")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateWSIResponse")
    public ProcessRequestOut statusUpdateWSI(
            @WebParam(name = "StatusUpdateData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "requestData")
            StatusUpdateData requestData);

    /**
     * 
     * @param requestData
     * @return
     *     returns ru.sample.qiwi.ProcessRequestOut
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesWSI")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesWSIResponse")
    public ProcessRequestOut joinUidResponsesWSI(
            @WebParam(name = "JoinUidResponsesData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "requestData")
            JoinUidResponsesData requestData);

    /**
     * 
     * @param requestData
     * @return
     *     returns ru.sample.qiwi.ProcessRequestOut
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesWSI")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesWSIResponse")
    public ProcessRequestOut joinApplicationResponsesWSI(
            @WebParam(name = "JoinApplicationResponsesData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "requestData")
            JoinApplicationResponsesData requestData);

}
