
package ru.sample.qiwi.soap.cre;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConnectorException", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService")
public class ConnectorException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConnectorExceptionDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConnectorException(String message, ConnectorExceptionDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConnectorException(String message, ConnectorExceptionDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.sample.qiwi.ConnectorExceptionDetail
     */
    public ConnectorExceptionDetail getFaultInfo() {
        return faultInfo;
    }

}
