
package ru.sample.qiwi.soap.cre;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConnectorService", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConnectorService {


    /**
     * 
     * @param responseId
     * @return
     *     returns ru.sample.qiwi.ConnectorResponse
     * @throws ConnectorException
     */
    @WebMethod(action = "urn:getSubjectData")
    @WebResult(name = "getSubjectDataout", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "getSubjectDataout")
    public ConnectorResponse getSubjectData(
            @WebParam(name = "responseId", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "responseId")
            String responseId)
        throws ConnectorException
    ;

    /**
     * 
     * @param businessRequest
     * @return
     *     returns ru.sample.qiwi.ConnectorResponse
     * @throws ConnectorException
     */
    @WebMethod(action = "urn:getBusiness")
    @WebResult(name = "getBusinessout", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "getBusinessout")
    public ConnectorResponse getBusiness(
            @WebParam(name = "businessRequest", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "businessRequest")
            ConnectorBusinessRequest businessRequest)
        throws ConnectorException
    ;

    /**
     * 
     * @param personRequest
     * @return
     *     returns ru.sample.qiwi.ConnectorResponse
     * @throws ConnectorException
     */
    @WebMethod(action = "urn:getPerson")
    @WebResult(name = "getPersonout", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "getPersonout")
    public ConnectorResponse getPerson(
            @WebParam(name = "personRequest", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "personRequest")
            ConnectorPersonRequest personRequest)
        throws ConnectorException
    ;

    /**
     * 
     * @param businessRequest
     * @return
     *     returns ru.sample.qiwi.ConnectorResponse
     * @throws ConnectorException
     */
    @WebMethod(action = "urn:getExpansionScore")
    @WebResult(name = "getExpansionScoreout", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "getExpansionScoreout")
    public ConnectorResponse getExpansionScore(
            @WebParam(name = "expansionScoreRequest", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "businessRequest")
            ExpansionScoreRequest businessRequest)
        throws ConnectorException
    ;

    /**
     * 
     * @param collateralAutoRequest
     * @return
     *     returns ru.sample.qiwi.ConnectorCollAutoResponse
     * @throws ConnectorException
     */
    @WebMethod(action = "urn:getCollateralAuto")
    @WebResult(name = "getCollateralAutoout", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "getCollateralAutoout")
    public ConnectorCollAutoResponse getCollateralAuto(
            @WebParam(name = "collateralAutoRequest", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "collateralAutoRequest")
            ConnectorCollAutoRequest collateralAutoRequest)
        throws ConnectorException
    ;

    /**
     * 
     * @param statReportRequest
     * @return
     *     returns ru.sample.qiwi.ConnectorResponse
     * @throws ConnectorException
     */
    @WebMethod(action = "urn:getStatReport")
    @WebResult(name = "getStatReportout", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "getStatReportout")
    public ConnectorResponse getStatReport(
            @WebParam(name = "statReportRequest", targetNamespace = "http://creditregistry.ru/2007/webservice/ConnectorService", partName = "statReportRequest")
            StatReportRequest statReportRequest)
        throws ConnectorException
    ;

}
